### ISSUE TITLE
Confused about missing variables？

### ISSUE THREAD

**Issue by isekeylabSunQixiang** [limhongki/Momentum_Net#1]
The variables `Mx`, `Mx_test`, `w`, 'w_test', `sino`, `sino_test` are all suddenly appeared, but I couldn't locate them source. I assume them are generated from a dataset. Is my assumption correct? If so, could you kindly guide me on how to generate dataset correctly?

**Comment by JeffFessler** [comment]
I'm not sure which script you are trying, but probably the script needs the data.  Like this one:
https://github.com/limhongki/Momentum_Net/blob/51aadf92ef756221714bfb65ce4a1f9893d7c6a0/func_test_momentum.m#L3
Hopefully Hongki still has the data somewhere!

**Comment by JeffFessler** [comment]
@isekeylabSunQixiang  I just wanted to let you know that we are trying to recover the missing data, or at least make documentation about the data requirements.
See #2 and stay tuned...

**Comment by qixiangsun-cwu** [comment]
Thank you, Professor Fessler. I appreciate your response, and I hope you had a great Dragon Boat Festival. I understand that Mx, Mx_test, w, and w_test are derived from the missing './data/testing_data(ctrecon,phantom).mat' file. I am genuinely interested in knowing how to generate these data: Mx, Mx_test, w, and w_test. I have attempted to generate them using other MATLAB code, but I am uncertain if it is correct. It would be greatly appreciated if you could provide the code for generating Mx, Mx_test, w, and w_test, if possible

> @isekeylabSunQixiang I just wanted to let you know that we are trying to recover the missing data, or at least make documentation about the data requirements. See #2 and stay tuned...

**Comment by JeffFessler** [comment]
We updated the README with a link to a "gofile.me" site.  Please try that.
